[tool.black]
line-length = 88
target-version = ['py35', 'py36', 'py37']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.github
    | \.mypy_cache
    | \.pytest_cache
    | src
    | exp/third_party
  )/
)
'''
